export const GET_ERRORS = 'GET_ERRORS';
export const USER_LOADING = 'USER_LOADING';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';

export const ADD_FLASH_MESSAGE = 'ADD_FLASH_MESSAGE';
export const DELETE_FLASH_MESSAGE = 'DELETE_FLASH_MESSAGE';

export const SET_GAME_MEMORY = 'SET_GAME_MEMORY';
export const RESET_GAME_MEMORY = 'DELETE_GAME_MEMORY'

export const INCREMENT_PLAYER = 'INCREMENT_PLAYER';
export const INCREMENT_COMPUTER = 'INCREMENT_COMPUTER';
export const SET_SCORE = 'SET_SCORE';
export const RESET_SCORE = 'RESET_SCORE';
